zone_names = { "airp", "alamo", "alta", "armyb", "banhamc", "banning", "beach", "bhamca", "bradp", "bradt", "burton", "calafb", "canny", "ccreak", "chamh", "chil", "chu", "cmsw", "cypre", "davis", "delbe", "delpe", "delsol", "desrt", "downt", "dtvine", "east_v", "eburo", "elgorl", "elysian", "galfish", "golf", "grapes", "greatc", "harmo", "hawick", "hors", "humlab", "jail", "koreat", "lact", "lago", "ldam", "legsqu", "lmesa", "lospuer", "mirr", "morn", "movie", "mtchil", "mtgordo", "mtjose", "murri", "nchu", "noose", "oceana", "palcov", "paleto", "palfor", "palhigh", "palmpow", "pbluff", "pbox", "procob", "rancho", "rglen", "richm", "rockf", "rtrak", "sanand", "sanchia", "sandy", "skid", "slab", "stad", "straw", "tatamo", "termina", "texti", "tongvah", "tongvav", "vcana", "vesp", "vine", "windf", "wvine", "zancudo", "zp_ort", "zq_uar", "isheist" }
zone_display_names = { "Los Santos International Airport", "Alamo Sea", "Alta", "Fort Zancudo", "Banham Canyon Dr", "Banning", "Vespucci Beach", "Banham Canyon", "Braddock Pass", "Braddock Tunnel", "Burton", "Calafia Bridge", "Raton Canyon", "Cassidy Creek", "Chamberlain Hills", "Vinewood Hills", "Chumash", "Chiliad Mountain State Wilderness", "Cypress Flats", "Davis", "Del Perro Beach", "Del Perro", "La Puerta", "Grand Senora Desert", "Downtown", "Downtown Vinewood", "East Vinewood", "El Burro Heights", "El Gordo Lighthouse", "Elysian Island", "Galilee", "GWC and Golfing Society", "Grapeseed", "Great Chaparral", "Harmony", "Hawick", "Vinewood Racetrack", "Humane Labs and Research", "Bolingbroke Penitentiary", "Little Seoul", "Land Act Reservoir", "Lago Zancudo", "Land Act Dam", "Legion Square", "La Mesa", "La Puerta", "Mirror Park", "Morningwood", "Richards Majestic", "Mount Chiliad", "Mount Gordo", "Mount Josiah", "Murrieta Heights", "North Chumash", "N.O.O.S.E", "Pacific Ocean", "Paleto Cove", "Paleto Bay", "Paleto Forest", "Palomino Highlands", "Palmer-Taylor Power Station", "Pacific Bluffs", "Pillbox Hill", "Procopio Beach", "Rancho", "Richman Glen", "Richman", "Rockford Hills", "Redwood Lights Track", "San Andreas", "San Chianski Mountain Range", "Sandy Shores", "Mission Row", "Stab City", "Maze Bank Arena", "Strawberry", "Tataviam Mountains", "Terminal", "Textile City", "Tongva Hills", "Tongva Valley", "Vespucci Canals", "Vespucci", "Vinewood", "Ron Alternates Wind Farm", "West Vinewood", "Zancudo River", "Port of South Los Santos", "Davis Quartz", "Cayo Perico" }

-- Credit to Senexis: https://github.com/Senexis/RDO-GG-Tunables/blob/main/public/data/daily_objectives.json https://github.com/Senexis/RDO-GG-Tunables/blob/main/public/data/weekly_objectives.json

daily_challenges = {
  "Participate in a Land Race.",
  "Participate in a Bike Race.",
  "Participate in an Air Race.",
  "Participate in a Sea Race.",
  "Participate in a Rally Race.",
  "Participate in a GTA Race.",
  "Participate in a Non-Contact Race.",
  "Participate in a Team Deathmatch.",
  "Participate in a Deathmatch.",
  "Participate in a Vehicle Deathmatch.",
  "Participate in a Parachute Jump.",
  "Participate in a Last Team Standing.",
  "Participate in a Capture - Contend.",
  "Participate in a Capture - Hold.",
  "Participate in a Capture - Raid.",
  "Participate in a Capture - GTA.",
  "Participate in a Versus Mission.",
  "Complete a Contact Mission.",
  "Participate in a Survival.",
  "Hold up a store.",
  "Complete a Gang Attack.",
  "Participate in an Impromptu Race.",
  "Participate in One on One Deathmatch.",
  "Go to the Movies.",
  "Fly under a bridge in an Air Race.",
  "Ride on one of the Fairground Rides.",
  "Steal a vehicle from the military base.",
  "Mod a vehicle at a car mod shop.",
  "Perform a Stunt Jump.",
  "Deliver an Export vehicle to Simeon.",
  "Collect a Bounty.",
  "Kill a player while Off the Radar.",
  "Kill a revealed player.",
  "Bribe the Cops then cause havoc.",
  "Call a Mugger on another player.",
  "Use some Bull Shark Testosterone.",
  "Collect an Ammo Drop.",
  "Play a game of Darts.",
  "Play a round of Golf.",
  "Play a match of Tennis.",
  "Challenge a player at Arm Wrestling.",
  "Go for a round at the Shooting Range.",
  "Complete a Flight School lesson.",
  "Kill 10 players.",
  "Destroy 10 vehicles.",
  "Steal 10 vehicles.",
  "Escape a 3 star Wanted Level.",
  "Fall for 325 feet and survive.",
  "Parachute from 650 feet.",
  "Deploy your parachute near the ground.",
  "Perform a wheelie for 10 seconds.",
  "Participate in a Capture.",
  "Participate in the Featured Series.",
  "Participate in the Adversary Series.",
  "Participate in the Stunt Series.",
  "Participate in the Special Race Series.",
  "Participate in the Transform Series.",
  "Participate in the SASS Series.",
  "Participate in the Arena War Series.",
  "Participate in the Bunker Series.",
  "Participate in the Race Series.",
  "Participate in the Survival Series.",
  "Participate in a King of the Hill.",
  "Participate in a Client Job.",
  "Participate in VIP Work.",
  "Participate in Club Work.",
  "Participate in a Clubhouse Contract.",
  "Participate in a Business Battle.",
  "Participate in a Freemode Event.",
  "Participate in a Freemode Challenge.",
  "Complete a Lowrider mission.",
  "Complete a Dispatch mission.",
  "Complete a Heist Setup.",
  "Complete a Heist Finale.",
  "Complete a Doomsday Heist Prep.",
  "Complete a Doomsday Heist Setup.",
  "Complete a Doomsday Heist Finale.",
  "Participate in Come Out To Play.",
  "Participate in Siege Mentality.",
  "Participate in Hasta La Vista.",
  "Participate in Cross the Line.",
  "Participate in Hunting Pack.",
  "Participate in Keep the Pace.",
  "Participate in Offense Defense.",
  "Participate in Relay.",
  "Participate in Slasher.",
  "Participate in Extraction.",
  "Participate in Beast vs. Slasher.",
  "Participate in Drop Zone.",
  "Participate in Till Death Do Us Part.",
  "Participate in Sumo.",
  "Participate in Inch By Inch.",
  "Participate in Trading Places.",
  "Participate in Power Play.",
  "Participate in Entourage.",
  "Participate in Slipstream.",
  "Participate in Lost vs Damned.",
  "Participate in Deadline.",
  "Participate in Kill Quota.",
  "Participate in Turf Wars.",
  "Participate in Vehicle Vendetta.",
  "Participate in Collection Time.",
  "Participate in Juggernaut.",
  "Participate in Resurrection.",
  "Participate in Tiny Racers.",
  "Participate in Dawn Raid.",
  "Participate in Overtime Rumble.",
  "Participate in Power Mad.",
  "Participate in Overtime Shootout.",
  "Participate in Motor Wars.",
  "Participate in Bombushka Run.",
  "Participate in Stockpile.",
  "Participate in The Vespucci Job.",
  "Participate in Hunting Pack (Remix).",
  "Participate in Trading Places (Remix).",
  "Participate in Running Back (Remix).",
  "Participate in Sumo (Remix).",
  "Participate in Running Back.",
  "Participate in Every Bullet Counts.",
  "Participate in Rhino Hunt.",
  "Participate in In and Out.",
  "Participate in Bomb Ball.",
  "Participate in Buzzer Beater.",
  "Participate in Carnage.",
  "Participate in Tag Team.",
  "Participate in Games Masters.",
  "Participate in Here Come the Monsters.",
  "Participate in Wreck It.",
  "Participate in Hot Bomb.",
  "Participate in Flag War.",
  "Play the Shooting Range at a Bunker.",
  "Hire a player for your Motorcycle Club.",
  "Hire a player for your Organization.",
  "Set yourself as Looking for Work.",
  "Set yourself as Looking for an MC.",
  "Resupply the Cocaine Lockup.",
  "Resupply the Weed Farm.",
  "Resupply the Counterfeit Cash Factory.",
  "Resupply the Meth Lab.",
  "Resupply the Document Forgery Office.",
  "Resupply the Bunker.",
  "Source Special Cargo.",
  "Source Air-Freight Cargo.",
  "Source Vehicle Cargo.",
  "Sell Special Cargo.",
  "Sell Air-Freight Cargo.",
  "Sell Weapons.",
  "Sell Cocaine.",
  "Sell Weed.",
  "Sell Counterfeit Cash.",
  "Sell Meth.",
  "Sell Forged Documents.",
  "Export Vehicle Cargo.",
  "Sell Goods from your Nightclub.",
  "Complete Club Management.",
  "Order a drink from a bar.",
  "Dance in a player owned Nightclub.",
  "Relax in a hot tub.",
  "Fly a Drone.",
  "Drive an RC Bandito.",
  "Go Scuba Diving.",
  "Have a snowball fight.",
  "Get a headshot with the Double-Action Revolver.",
  "Rampage with the Stone Hatchet.",
  "Modify a MKII weapon.",
  "Modify an aircraft at your Hangar.",
  "Modify a vehicle at your Arena Workshop.",
  "Modify a vehicle at Benny's Original Motor Works.",
  "Modify a vehicle in the Mobile Operations Center.",
  "Modify a vehicle in the Avenger.",
  "Modify a vehicle at the Clubhouse.",
  "Visit The Diamond Casino & Resort.",
  "Complete a mission for The Diamond Casino & Resort.",
  "Spin the Lucky Wheel.",
  "Complete a Special Vehicle Work.",
  "Complete a Simeon Repo.",
  "Complete a Diamond Casino Heist Prep.",
  "Complete The Diamond Casino Heist Finale.",
  "Play any game in an Arcade.",
  "Dance in The Music Locker.",
  "Dance at the Cayo Perico beach party.",
  "Participate in the Street Race Series.",
  "Participate in the Pursuit Series.",
  "Visit the LS Car Meet.",
  "Visit the LS Car Meet with a Personal Vehicle.",
  "Drive an LS Car Meet vehicle in the Test Track.",
  "Spectate the Test Track inside the LS Car Meet.",
  "Participate in a Sprint at the LS Car Meet.",
  "Deliver an Exotic Exports Vehicle to the Docks.",
  "Complete a Planning Work mission.",
  "Complete a Contract for KDJ and Sessanta.",
  "Participate in a Scramble at the LS Car Meet.",
  "Participate in a Head-to-Head at the LS Car Meet.",
  "Complete 1 lap of the Time Trial at the LS Car Meet.",
  "Visit Record A Studios.",
  "Complete a Security Contract.",
  "Complete a Payphone Hit.",
  "Complete an Investigation for Dr. Dre.",
  "Complete a Short Trip.",
  "Participate in a HSW Race.",
  "Participate in the Community Series.",
  "Participate in the Cayo Perico Series.",
  "Participate in Assault on Cayo Perico.",
  "Visit The Freakshop.",
  "Complete a First Dose mission.",
  "Complete a Last Dose mission.",
  "Complete a Fooligan Job.",
  "Complete one fare during Taxi Work.",
  "Raid a Stash House.",
  "Collect G's Cache.",
  "Sell any product to a Street Dealer.",
  "Complete a Junk Energy Time Trial.",
  "Complete a Resupply Mission for the Acid Lab.",
  "Sell Acid.",
  "Complete a Project Overthrow mission.",
  "Complete an LSA Operation.",
  "Complete Slush Fund.",
  "Complete Scene of the Crime.",
  "Participate in the Drag Race Series.",
  "Participate in the Drift Race Series.",
  "Recover a vehicle using the Tow Truck.",
  "Photograph an animal for the LS Tourist Board."
}

weekly_challenges = {
  "Complete 5 Fooligan Jobs.",
  "Complete the Assassination Bonus on 5 Payphone Hits.",
  "Complete 10 Security Contracts.",
  "Complete 3 Short Trips.",
  "Complete Don't Fuck with Dre.",
  "Complete the Elite Challenge for The Cayo Perico Heist.",
  "Complete The Cayo Perico Heist undetected.",
  "Complete The Cayo Perico Heist without dying.",
  "Complete The Cayo Perico Heist 2 times.",
  "Complete any Diamond Casino Heist Elite Challenge.",
  "Complete The Diamond Casino Heist 2 times.",
  "Rob the Daily Vault in The Diamond Casino Heist.",
  "Complete 5 Casino Works for Agatha Baker.",
  "Complete the Elite Challenge for The Data Breaches.",
  "Complete the Elite Challenge for The Bogdan Problem.",
  "Complete the Elite Challenge for The Doomsday Scenario.",
  "Complete The Doomsday Scenario.",
  "Participate in 10 Arena War modes.",
  "Win 3 Arena War modes.",
  "Complete 5 LSA Operations on Specialist.",
  "Complete 1 Project Overthrow Missions.",
  "Complete 5 Mobile Operations.",
  "Complete 5 Mobile Operations on Hard difficulty.",
  "Complete 5 Special Vehicle Works on Hard difficulty.",
  "Complete 5 Special Vehicle Works.",
  "Complete 10 Clubhouse Contracts.",
  "Complete 5 Motorcycle Club Challenges.",
  "Participate in 5 VIP Challenges.",
  "Complete 3 Heist finales.",
  "Complete all 10 waves of a Survival.",
  "Survive 5 waves in a Survival without dying.",
  "Participate in 6 Drag Races.",
  "Win 5 Races.",
  "Win 5 LS Car Meet Races.",
  "Beat the par time in 3 Time Trials.",
  "Beat the par time in 3 RC Bandito Time Trials.",
  "Win 3 Deathmatches.",
  "Win 3 Team Deathmatches.",
  "Win 3 Drag or Drift Races.",
  "Win 5 Adversary Modes.",
  "Participate in 6 Drift Races.",
  "Complete 25 fares during Taxi Work.",
  "Achieve a gold medal in 10 Junk Energy Skydives.",
  "Beat the par time in 3 Junk Energy Time Trials.",
  "Collect 3 player bounties.",
  "Deliver 3 Export vehicles to Simeon.",
  "Steal from 3 Stash Houses.",
  "Collect 3 G's Caches.",
  "Discover 3 Shipwrecks.",
  "Sell to 3 Street Dealers.",
  "Complete 3 Last Dose Missions.",
  "Complete 3 First Dose Missions.",
  "Collect 10 Hidden Caches.",
  "Complete 5 CEO or VIP Works.",
  "Win 3 Stunt Races.",
  "Win 3 Hotring Series Races.",
  "Win 3 Open Wheel Races.",
  "Win 3 RC Bandito Races.",
  "Win 3 Pursuit Races.",
  "Complete 5 Terrorbyte Client Jobs.",
  "Complete 5 Nightclub Management Missions.",
  "Sell $3,000,000 across all businesses.",
  "Earn $100,000 in wages as an Associate or Bodyguard.",
  "Complete 3 Business Resupply Missions.",
  "Complete 3 Gerald's Last Play Missions.",
  "Complete 3 Premium Deluxe Repo Work Missions.",
  "Complete 3 A Superyacht Life Missions.",
  "Complete 3 Bunker Research Missions.",
  "Complete the Ammu-Nation Contract 3 times.",
  "Complete a Salvage Yard Robbery without dying.",
  "Deliver 10 Exotic Exports vehicles.",
  "Complete 3 Auto Shop Contract Finales.",
  "Deliver 3 vehicles for the Auto Shop Service.",
  "Complete 3 Salvage Yard Robberies.",
  "Complete Scene of the Crime.",
  "Recover 10 vehicles using the Tow Truck.",
  "Photograph 10 animals for Shoot Animals photography.",
  "Create a Job in the Job Creator.",
  "Steal from 2 Armored Trucks.",
  "Take part in 5 Freemode Challenges.",
  "Participate in 5 Freemode Events.",
  "Successfully Complete 10 Stunt Jumps.",
  "Earn $50,000 Arcade daily earnings.",
  "Complete 5 Business Battles.",
  "Complete 3 Last Dose Missions on Hard.",
  "Eat 3 peyote.",
  "Earn $2,000,000 from selling Special Cargo.",
  "Earn $2,000,000 from selling Vehicle Cargo.",
  "Earn $50,000 from Nightclub daily earnings.",
  "Earn $2,000,000 from selling Product.",
  "Complete The Data Breaches.",
  "Complete The Bogdan Problem.",
  "Complete 3 First Dose Missions on Hard.",
  "Win in 3 Snowball Deathmatches.",
  "Win Beast vs. Slasher.",
  "Fight off the Gooch.",
  "Kill your clone in Clone Slasher."
}