vehicle_names = {
	"adder",
	"airbus",
	"airtug",
	"akula",
	"akuma",
	"alkonost",
	"alpha",
	"alphaz1",
	"ambulance",
	"annihilator",
	"annihilator2",
	"apc",
	"arbitergt",
	"ardent",
	"armytanker",
	"armytrailer",
	"armytrailer2",
	"asbo",
	"asea",
	"asea2",
	"asterope",
	"astron",
	"astron2",
	"autarch",
	"avarus",
	"avenger",
	"avenger2",
	"avenger3",
	"avenger4",
	"avisa",
	"bagger",
	"baletrailer",
	"baller",
	"baller2",
	"baller3",
	"baller4",
	"baller5",
	"baller6",
	"baller7",
	"banshee",
	"banshee2",
	"barracks",
	"barracks2",
	"barracks3",
	"barrage",
	"bati",
	"bati2",
	"benson",
	"besra",
	"bestiagts",
	"bf400",
	"bfinjection",
	"biff",
	"bifta",
	"bison",
	"bison2",
	"bison3",
	"bjxl",
	"blade",
	"blazer",
	"blazer2",
	"blazer3",
	"blazer4",
	"blazer5",
	"blimp",
	"blimp2",
	"blimp3",
	"blista",
	"blista2",
	"blista3",
	"bmx",
	"boattrailer",
	"bobcatxl",
	"bodhi2",
	"bombushka",
	"boor",
	"boxville",
	"boxville2",
	"boxville3",
	"boxville4",
	"boxville5",
	"brawler",
	"brickade",
	"brickade2",
	"brigham",
	"brioso",
	"brioso2",
	"brioso3",
	"broadway",
	"bruiser",
	"bruiser2",
	"bruiser3",
	"brutus",
	"brutus2",
	"brutus3",
	"btype",
	"btype2",
	"btype3",
	"buccaneer",
	"buccaneer2",
	"buffalo",
	"buffalo2",
	"buffalo3",
	"buffalo4",
	"buffalo5",
	"bulldozer",
	"bullet",
	"burrito",
	"burrito2",
	"burrito3",
	"burrito4",
	"burrito5",
	"bus",
	"buzzard",
	"buzzard2",
	"cablecar",
	"caddy",
	"caddy2",
	"caddy3",
	"calico",
	"camper",
	"caracara",
	"caracara2",
	"carbonizzare",
	"carbonrs",
	"cargobob",
	"cargobob2",
	"cargobob3",
	"cargobob4",
	"cargoplane",
	"cargoplane2",
	"casco",
	"cavalcade",
	"cavalcade2",
	"cerberus",
	"cerberus2",
	"cerberus3",
	"champion",
	"cheburek",
	"cheetah",
	"cheetah2",
	"chernobog",
	"chimera",
	"chino",
	"chino2",
	"cinquemila",
	"cliffhanger",
	"clique",
	"clique2",
	"club",
	"coach",
	"cog55",
	"cog552",
	"cogcabrio",
	"cognoscenti",
	"cognoscenti2",
	"comet2",
	"comet3",
	"comet4",
	"comet5",
	"comet6",
	"comet7",
	"conada",
	"conada2",
	"contender",
	"coquette",
	"coquette2",
	"coquette3",
	"coquette4",
	"corsita",
	"coureur",
	"cruiser",
	"crusader",
	"cuban800",
	"cutter",
	"cyclone",
	"cyclone2",
	"cypher",
	"daemon",
	"daemon2",
	"deathbike",
	"deathbike2",
	"deathbike3",
	"defiler",
	"deity",
	"deluxo",
	"deveste",
	"deviant",
	"diablous",
	"diablous2",
	"dilettante",
	"dilettante2",
	"dinghy",
	"dinghy2",
	"dinghy3",
	"dinghy4",
	"dinghy5",
	"dloader",
	"docktrailer",
	"docktug",
	"dodo",
	"dominator",
	"dominator2",
	"dominator3",
	"dominator4",
	"dominator5",
	"dominator6",
	"dominator7",
	"dominator8",
	"double",
	"drafter",
	"draugur",
	"dubsta",
	"dubsta2",
	"dubsta3",
	"dukes",
	"dukes2",
	"dukes3",
	"dump",
	"dune",
	"dune2",
	"dune3",
	"dune4",
	"dune5",
	"duster",
	"dynasty",
	"elegy",
	"elegy2",
	"ellie",
	"emerus",
	"emperor",
	"emperor2",
	"emperor3",
	"enduro",
	"entity2",
	"entity3",
	"entityxf",
	"esskey",
	"eudora",
	"euros",
	"everon",
	"everon2",
	"exemplar",
	"f620",
	"faction",
	"faction2",
	"faction3",
	"fagaloa",
	"faggio",
	"faggio2",
	"faggio3",
	"fbi",
	"fbi2",
	"fcr",
	"fcr2",
	"felon",
	"felon2",
	"feltzer2",
	"feltzer3",
	"firetruk",
	"fixter",
	"flashgt",
	"flatbed",
	"fmj",
	"forklift",
	"formula",
	"formula2",
	"fq2",
	"freecrawler",
	"freight",
	"freightcar",
	"freightcar2",
	"freightcont1",
	"freightcont2",
	"freightgrain",
	"freighttrailer",
	"frogger",
	"frogger2",
	"fugitive",
	"furia",
	"furoregt",
	"fusilade",
	"futo",
	"futo2",
	"gargoyle",
	"gauntlet",
	"gauntlet2",
	"gauntlet3",
	"gauntlet4",
	"gauntlet5",
	"gauntlet6",
	"gb200",
	"gburrito",
	"gburrito2",
	"glendale",
	"glendale2",
	"gp1",
	"graintrailer",
	"granger",
	"granger2",
	"greenwood",
	"gresley",
	"growler",
	"gt500",
	"guardian",
	"habanero",
	"hakuchou",
	"hakuchou2",
	"halftrack",
	"handler",
	"hauler",
	"hauler2",
	"havok",
	"hellion",
	"hermes",
	"hexer",
	"hotknife",
	"hotring",
	"howard",
	"hunter",
	"huntley",
	"hustler",
	"hydra",
	"ignus",
	"ignus2",
	"imorgon",
	"impaler",
	"impaler2",
	"impaler3",
	"impaler4",
	"imperator",
	"imperator2",
	"imperator3",
	"inductor",
	"inductor2",
	"infernus",
	"infernus2",
	"ingot",
	"innovation",
	"insurgent",
	"insurgent2",
	"insurgent3",
	"intruder",
	"issi2",
	"issi3",
	"issi4",
	"issi5",
	"issi6",
	"issi7",
	"issi8",
	"italigtb",
	"italigtb2",
	"italigto",
	"italirsx",
	"iwagen",
	"jackal",
	"jb700",
	"jb7002",
	"jester",
	"jester2",
	"jester3",
	"jester4",
	"jet",
	"jetmax",
	"journey",
	"journey2",
	"jubilee",
	"jugular",
	"kalahari",
	"kamacho",
	"kanjo",
	"kanjosj",
	"khamelion",
	"khanjali",
	"komoda",
	"kosatka",
	"krieger",
	"kuruma",
	"kuruma2",
	"l35",
	"landstalker",
	"landstalker2",
	"lazer",
	"le7b",
	"lectro",
	"lguard",
	"limo2",
	"lm87",
	"locust",
	"longfin",
	"lurcher",
	"luxor",
	"luxor2",
	"lynx",
	"mamba",
	"mammatus",
	"manana",
	"manana2",
	"manchez",
	"manchez2",
	"manchez3",
	"marquis",
	"marshall",
	"massacro",
	"massacro2",
	"maverick",
	"menacer",
	"mesa",
	"mesa2",
	"mesa3",
	"metrotrain",
	"michelli",
	"microlight",
	"miljet",
	"minitank",
	"minivan",
	"minivan2",
	"mixer",
	"mixer2",
	"mogul",
	"molotok",
	"monroe",
	"monster",
	"monster3",
	"monster4",
	"monster5",
	"monstrociti",
	"moonbeam",
	"moonbeam2",
	"mower",
	"mule",
	"mule2",
	"mule3",
	"mule4",
	"mule5",
	"nebula",
	"nemesis",
	"neo",
	"neon",
	"nero",
	"nero2",
	"nightblade",
	"nightshade",
	"nightshark",
	"nimbus",
	"ninef",
	"ninef2",
	"nokota",
	"novak",
	"omnis",
	"omnisegt",
	"openwheel1",
	"openwheel2",
	"oppressor",
	"oppressor2",
	"oracle",
	"oracle2",
	"osiris",
	"outlaw",
	"packer",
	"panthere",
	"panto",
	"paradise",
	"paragon",
	"paragon2",
	"pariah",
	"patriot",
	"patriot2",
	"patriot3",
	"patrolboat",
	"pbus",
	"pbus2",
	"pcj",
	"penetrator",
	"penumbra",
	"penumbra2",
	"peyote",
	"peyote2",
	"peyote3",
	"pfister811",
	"phantom",
	"phantom2",
	"phantom3",
	"phoenix",
	"picador",
	"pigalle",
	"police",
	"police2",
	"police3",
	"police4",
	"policeb",
	"policeold1",
	"policeold2",
	"policet",
	"polmav",
	"pony",
	"pony2",
	"postlude",
	"pounder",
	"pounder2",
	"powersurge",
	"prairie",
	"pranger",
	"predator",
	"premier",
	"previon",
	"primo",
	"primo2",
	"proptrailer",
	"prototipo",
	"pyro",
	"r300",
	"radi",
	"raiden",
	"raiju",
	"raketrailer",
	"rallytruck",
	"rancherxl",
	"rancherxl2",
	"rapidgt",
	"rapidgt2",
	"rapidgt3",
	"raptor",
	"ratbike",
	"ratel",
	"ratloader",
	"ratloader2",
	"rcbandito",
	"reaper",
	"rebel",
	"rebel2",
	"rebla",
	"reever",
	"regina",
	"remus",
	"rentalbus",
	"retinue",
	"retinue2",
	"revolter",
	"rhapsody",
	"rhinehart",
	"rhino",
	"riata",
	"riot",
	"riot2",
	"ripley",
	"rocoto",
	"rogue",
	"romero",
	"rrocket",
	"rt3000",
	"rubble",
	"ruffian",
	"ruiner",
	"ruiner2",
	"ruiner3",
	"ruiner4",
	"rumpo",
	"rumpo2",
	"rumpo3",
	"ruston",
	"s80",
	"s95",
	"sabregt",
	"sabregt2",
	"sadler",
	"sadler2",
	"sanchez",
	"sanchez2",
	"sanctus",
	"sandking",
	"sandking2",
	"savage",
	"savestra",
	"sc1",
	"scarab",
	"scarab2",
	"scarab3",
	"schafter2",
	"schafter3",
	"schafter4",
	"schafter5",
	"schafter6",
	"schlagen",
	"schwarzer",
	"scorcher",
	"scramjet",
	"scrap",
	"seabreeze",
	"seashark",
	"seashark2",
	"seashark3",
	"seasparrow",
	"seasparrow2",
	"seasparrow3",
	"seminole",
	"seminole2",
	"sentinel",
	"sentinel2",
	"sentinel3",
	"sentinel4",
	"serrano",
	"seven70",
	"shamal",
	"sheava",
	"sheriff",
	"sheriff2",
	"shinobi",
	"shotaro",
	"skylift",
	"slamtruck",
	"slamvan",
	"slamvan2",
	"slamvan3",
	"slamvan4",
	"slamvan5",
	"slamvan6",
	"sm722",
	"sovereign",
	"specter",
	"specter2",
	"speeder",
	"speeder2",
	"speedo",
	"speedo2",
	"speedo4",
	"speedo5",
	"squaddie",
	"squalo",
	"stafford",
	"stalion",
	"stalion2",
	"stanier",
	"starling",
	"stinger",
	"stingergt",
	"stingertt",
	"stockade",
	"stockade3",
	"stratum",
	"streamer216",
	"streiter",
	"stretch",
	"strikeforce",
	"stromberg",
	"stryder",
	"stunt",
	"submersible",
	"submersible2",
	"sugoi",
	"sultan",
	"sultan2",
	"sultan3",
	"sultanrs",
	"suntrap",
	"superd",
	"supervolito",
	"supervolito2",
	"surano",
	"surfer",
	"surfer2",
	"surfer3",
	"surge",
	"swift",
	"swift2",
	"swinger",
	"t20",
	"taco",
	"tahoma",
	"tailgater",
	"tailgater2",
	"taipan",
	"tampa",
	"tampa2",
	"tampa3",
	"tanker",
	"tanker2",
	"tankercar",
	"taxi",
	"technical",
	"technical2",
	"technical3",
	"tempesta",
	"tenf",
	"tenf2",
	"terbyte",
	"tezeract",
	"thrax",
	"thrust",
	"thruster",
	"tigon",
	"tiptruck",
	"tiptruck2",
	"titan",
	"toreador",
	"torero",
	"torero2",
	"tornado",
	"tornado2",
	"tornado3",
	"tornado4",
	"tornado5",
	"tornado6",
	"toro",
	"toro2",
	"toros",
	"tourbus",
	"towtruck",
	"towtruck2",
	"tr2",
	"tr3",
	"tr4",
	"tractor",
	"tractor2",
	"tractor3",
	"trailerlarge",
	"trailerlogs",
	"trailers",
	"trailers2",
	"trailers3",
	"trailers4",
	"trailersmall",
	"trailersmall2",
	"trash",
	"trash2",
	"trflat",
	"tribike",
	"tribike2",
	"tribike3",
	"trophytruck",
	"trophytruck2",
	"tropic",
	"tropic2",
	"tropos",
	"tug",
	"tula",
	"tulip",
	"tulip2",
	"turismo2",
	"turismor",
	"tvtrailer",
	"tyrant",
	"tyrus",
	"utillitruck",
	"utillitruck2",
	"utillitruck3",
	"vacca",
	"vader",
	"vagner",
	"vagrant",
	"valkyrie",
	"valkyrie2",
	"vamos",
	"vectre",
	"velum",
	"velum2",
	"verlierer2",
	"verus",
	"vestra",
	"vetir",
	"veto",
	"veto2",
	"vigero",
	"vigero2",
	"vigilante",
	"vindicator",
	"virgo",
	"virgo2",
	"virgo3",
	"virtue",
	"viseris",
	"visione",
	"volatol",
	"volatus",
	"voltic",
	"voltic2",
	"voodoo",
	"voodoo2",
	"vortex",
	"vstr",
	"warrener",
	"warrener2",
	"washington",
	"wastelander",
	"weevil",
	"weevil2",
	"windsor",
	"windsor2",
	"winky",
	"wolfsbane",
	"xa21",
	"xls",
	"xls2",
	"yosemite",
	"yosemite2",
	"yosemite3",
	"youga",
	"youga2",
	"youga3",
	"youga4",
	"z190",
	"zeno",
	"zentorno",
	"zhaba",
	"zion",
	"zion2",
	"zion3",
	"zombiea",
	"zombieb",
	"zorrusso",
	"zr350",
	"zr380",
	"zr3802",
	"zr3803",
	"ztype"
}

vehicle_display_names = {
	"Truffade Adder",
	"Airport Bus",
	"Airtug",
	"Akula",
	"Dinka Akuma",
	"RO-86 Alkonost",
	"Albany Alpha",
	"Buckingham Alpha-Z1",
	"Ambulance",
	"Annihilator",
	"Annihilator Stealth",
	"HVY APC",
	"Imponte Arbiter GT",
	"Ocelot Ardent",
	"Army Trailer",
	"Army Trailer",
	"Army Trailer",
	"Maxwell Asbo",
	"Declasse Asea",
	"Declasse Asea",
	"Karin Asterope",
	"Pfister Astron",
	"Pfister Astron Custom",
	"Overflod Autarch",
	"LCC Avarus",
	"Mammoth Avenger",
	"Mammoth Avenger",
	"Mammoth Avenger",
	"Mammoth Avenger",
	"Kraken Avisa",
	"Western Bagger",
	"Baletrailer",
	"Gallivanter Baller",
	"Gallivanter Baller",
	"Gallivanter Baller LE",
	"Gallivanter Baller LE LWB",
	"Gallivanter Baller LE (Armored)",
	"Gallivanter Baller LE LWB (Armored)",
	"Gallivanter Baller ST",
	"Bravado Banshee",
	"Bravado Banshee 900R",
	"Barracks",
	"HVY Barracks Semi",
	"Barracks",
	"Barrage",
	"Pegassi Bati 801",
	"Pegassi Bati 801RR",
	"Vapid Benson",
	"Western Besra",
	"Grotti Bestia GTS",
	"Nagasaki BF400",
	"BF Injection",
	"HVY Biff",
	"BF Bifta",
	"Bravado Bison",
	"Bravado Bison",
	"Bravado Bison",
	"Karin BeeJay XL",
	"Vapid Blade",
	"Nagasaki Blazer",
	"Nagasaki Blazer Lifeguard",
	"Nagasaki Hot Rod Blazer",
	"Nagasaki Street Blazer",
	"Nagasaki Blazer Aqua",
	"Atomic Blimp",
	"Xero Blimp",
	"Blimp",
	"Dinka Blista",
	"Dinka Blista Compact",
	"Dinka Go Go Monkey Blista",
	"BMX",
	"Boat Trailer",
	"Vapid Bobcat XL",
	"Canis Bodhi",
	"RM-10 Bombushka",
	"Karin Boor",
	"Brute Boxville",
	"Boxville",
	"Brute Boxville",
	"Brute Boxville",
	"Armored Boxville",
	"Coil Brawler",
	"MTL Brickade",
	"MTL Brickade 6x6",
	"Albany Brigham",
	"Grotti Brioso R/A",
	"Grotti Brioso 300",
	"Grotti Brioso 300 Widebody",
	"Classique Broadway",
	"Benefactor Apocalypse Bruiser",
	"Benefactor Future Shock Bruiser",
	"Benefactor Nightmare Bruiser",
	"Declasse Apocalypse Brutus",
	"Declasse Future Shock Brutus",
	"Declasse Nightmare Brutus",
	"Albany Roosevelt",
	"Albany Fränken Stange",
	"Albany Roosevelt Valor",
	"Albany Buccaneer",
	"Albany Buccaneer Custom",
	"Bravado Buffalo",
	"Bravado Buffalo S",
	"Bravado Sprunk Buffalo",
	"Bravado Buffalo STX",
	"Bravado Buffalo EVX",
	"HVY Dozer",
	"Vapid Bullet",
	"Declasse Burrito",
	"Declasse Bugstars Burrito",
	"Declasse Burrito",
	"Declasse Burrito",
	"Declasse Burrito",
	"Bus",
	"Buzzard Attack Chopper",
	"Buzzard",
	"Cable Car",
	"Caddy",
	"Caddy",
	"Caddy",
	"Karin Calico GTF",
	"Brute Camper",
	"Vapid Caracara",
	"Vapid Caracara 4x4",
	"Grotti Carbonizzare",
	"Nagasaki Carbon RS",
	"Cargobob",
	"Cargobob",
	"Cargobob",
	"Cargobob",
	"Cargo Plane",
	"Cargo Plane",
	"Lampadati Casco",
	"Albany Cavalcade",
	"Albany Cavalcade",
	"MTL Apocalypse Cerberus",
	"MTL Future Shock Cerberus",
	"MTL Nightmare Cerberus",
	"Dewbauchee Champion",
	"RUNE Cheburek",
	"Grotti Cheetah",
	"Grotti Cheetah Classic",
	"Chernobog",
	"Nagasaki Chimera",
	"Vapid Chino",
	"Vapid Chino Custom",
	"Lampadati Cinquemila",
	"Western Cliffhanger",
	"Vapid Clique",
	"Vapid Clique Wagon",
	"BF Club",
	"Dashound",
	"Enus Cognoscenti 55",
	"Enus Cognoscenti 55 (Armored)",
	"Enus Cognoscenti Cabrio",
	"Enus Cognoscenti",
	"Enus Cognoscenti (Armored)",
	"Pfister Comet",
	"Pfister Comet Retro Custom",
	"Pfister Comet Safari",
	"Pfister Comet SR",
	"Pfister Comet S2",
	"Pfister Comet S2 Cabrio",
	"Buckingham Conada",
	"Buckingham Weaponized Conada",
	"Vapid Contender",
	"Invetero Coquette",
	"Invetero Coquette Classic",
	"Invetero Coquette BlackFin",
	"Invetero Coquette D10",
	"Lampadati Corsita",
	"Penaud La Coureuse",
	"Cruiser",
	"Canis Crusader",
	"Cuban 800",
	"HVY Cutter",
	"Coil Cyclone",
	"Coil Cyclone II",
	"Ubermacht Cypher",
	"Western Daemon",
	"Western Daemon",
	"Western Apocalypse Deathbike",
	"Western Future Shock Deathbike",
	"Western Nightmare Deathbike",
	"Shitzu Defiler",
	"Enus Deity",
	"Imponte Deluxo",
	"Principe Deveste Eight",
	"Schyster Deviant",
	"Principe Diabolus",
	"Principe Diabolus Custom",
	"Karin Dilettante",
	"Karin Dilettante",
	"Nagasaki Dinghy",
	"Nagasaki Dinghy",
	"Nagasaki Dinghy",
	"Nagasaki Dinghy",
	"Nagasaki Weaponized Dinghy",
	"Bravado Duneloader",
	"Dock Trailer",
	"Docktug",
	"Mammoth Dodo",
	"Vapid Dominator",
	"Vapid Pisswasser Dominator",
	"Vapid Dominator GTX",
	"Vapid Apocalypse Dominator",
	"Vapid Future Shock Dominator",
	"Vapid Nightmare Dominator",
	"Vapid Dominator ASP",
	"Vapid Dominator GTT",
	"Dinka Double-T",
	"Obey 8F Drafter",
	"Declasse Draugur",
	"Benefactor Dubsta",
	"Benefactor Dubsta",
	"Benefactor Dubsta 6x6",
	"Imponte Dukes",
	"Imponte Duke O'Death",
	"Imponte Beater Dukes",
	"HVY Dump",
	"BF Dune Buggy",
	"Space Docker",
	"BF Dune FAV",
	"Ramp Buggy",
	"Ramp Buggy",
	"Duster",
	"Weeny Dynasty",
	"Annis Elegy Retro Custom",
	"Annis Elegy RH8",
	"Vapid Ellie",
	"Progen Emerus",
	"Albany Emperor",
	"Albany Emperor",
	"Albany Emperor",
	"Dinka Enduro",
	"Overflod Entity XXR",
	"Overflod Entity MT",
	"Overflod Entity XF",
	"Pegassi Esskey",
	"Willard Eudora",
	"Annis Euros",
	"Karin Everon",
	"Karin Hotring Everon",
	"Dewbauchee Exemplar",
	"Ocelot F620",
	"Willard Faction",
	"Willard Faction Custom",
	"Willard Faction Custom Donk",
	"Vulcar Fagaloa",
	"Pegassi Faggio Sport",
	"Pegassi Faggio",
	"Pegassi Faggio Mod",
	"FIB",
	"FIB",
	"Pegassi FCR 1000",
	"Pegassi FCR 1000 Custom",
	"Lampadati Felon",
	"Lampadati Felon GT",
	"Benefactor Feltzer",
	"Benefactor Feltzer Classic",
	"MTL Fire Truck",
	"Fixter",
	"Vapid Flash GT",
	"MTL Flatbed",
	"Vapid FMJ",
	"HVY Forklift",
	"Progen PR4",
	"Ocelot R88",
	"Fathom FQ 2",
	"Canis Freecrawler",
	"Freight Train",
	"Freight Train",
	"Freight Train",
	"Freight Train",
	"Freight Train",
	"Freight Train",
	"Freight Trailer",
	"Frogger",
	"Frogger",
	"Cheval Fugitive",
	"Grotti Furia",
	"Lampadati Furore GT",
	"Schyster Fusilade",
	"Karin Futo",
	"Karin Futo GTX",
	"Western Gargoyle",
	"Bravado Gauntlet",
	"Bravado Redwood Gauntlet",
	"Bravado Gauntlet Classic",
	"Bravado Gauntlet Hellfire",
	"Bravado Gauntlet Classic Custom",
	"Bravado Hotring Hellfire",
	"Vapid GB200",
	"Declasse Gang Burrito",
	"Declasse Gang Burrito",
	"Benefactor Glendale",
	"Benefactor Glendale Custom",
	"Progen GP1",
	"Graintrailer",
	"Declasse Granger",
	"Declasse Granger 3600LX",
	"Bravado Greenwood",
	"Bravado Gresley",
	"Pfister Growler",
	"Grotti GT500",
	"Vapid Guardian",
	"Emperor Habanero",
	"Shitzu Hakuchou",
	"Shitzu Hakuchou Drag",
	"Bravado Half-track",
	"Dock Handler",
	"JoBuilt Hauler",
	"JoBuilt Hauler Custom",
	"Nagasaki Havok",
	"Annis Hellion",
	"Albany Hermes",
	"LCC Hexer",
	"Vapid Hotknife",
	"Declasse Hotring Sabre",
	"Buckingham Howard NX-25",
	"FH-1 Hunter",
	"Enus Huntley S",
	"Vapid Hustler",
	"Mammoth Hydra",
	"Pegassi Ignus",
	"Pegassi Weaponized Ignus",
	"Overflod Imorgon",
	"Declasse Impaler",
	"Declasse Apocalypse Impaler",
	"Declasse Future Shock Impaler",
	"Declasse Nightmare Impaler",
	"Vapid Apocalypse Imperator",
	"Vapid Future Shock Imperator",
	"Vapid Nightmare Imperator",
	"Inductor",
	"Junk Energy Inductor",
	"Pegassi Infernus",
	"Pegassi Infernus Classic",
	"Vulcar Ingot",
	"LCC Innovation",
	"HVY Insurgent Pick-Up",
	"HVY Insurgent",
	"HVY Insurgent Pick-Up Custom",
	"Karin Intruder",
	"Weeny Issi",
	"Weeny Issi Classic",
	"Weeny Apocalypse Issi",
	"Weeny Future Shock Issi",
	"Weeny Nightmare Issi",
	"Weeny Issi Sport",
	"Weeny Issi Rally",
	"Progen Itali GTB",
	"Progen Itali GTB Custom",
	"Grotti Itali GTO",
	"Grotti Itali RSX",
	"Obey I-Wagen",
	"Ocelot Jackal",
	"Dewbauchee JB 700",
	"Dewbauchee JB 700W",
	"Dinka Jester",
	"Dinka Jester (Racecar)",
	"Dinka Jester Classic",
	"Dinka Jester RR",
	"Jet",
	"Shitzu Jetmax",
	"Zirconium Journey",
	"Zirconium Journey II",
	"Enus Jubilee",
	"Ocelot Jugular",
	"Canis Kalahari",
	"Canis Kamacho",
	"Dinka Blista Kanjo",
	"Dinka Kanjo SJ",
	"Hijak Khamelion",
	"TM-02 Khanjali",
	"Lampadati Komoda",
	"RUNE Kosatka",
	"Benefactor Krieger",
	"Karin Kuruma",
	"Karin Kuruma (Armored)",
	"Declasse Walton L35",
	"Dundreary Landstalker",
	"Dundreary Landstalker XL",
	"P-996 LAZER",
	"Annis RE-7B",
	"Principe Lectro",
	"Declasse Lifeguard",
	"Benefactor Turreted Limo",
	"Benefactor LM87",
	"Ocelot Locust",
	"Shitzu Longfin",
	"Albany Lurcher",
	"Buckingham Luxor",
	"Buckingham Luxor Deluxe",
	"Ocelot Lynx",
	"Declasse Mamba",
	"Mammatus",
	"Albany Manana",
	"Albany Manana Custom",
	"Maibatsu Manchez",
	"Maibatsu Manchez Scout",
	"Maibatsu Manchez Scout C",
	"Dinka Marquis",
	"Cheval Marshall",
	"Dewbauchee Massacro",
	"Dewbauchee Massacro (Racecar)",
	"Maverick",
	"HVY Menacer",
	"Canis Mesa",
	"Canis Mesa",
	"Canis Mesa",
	"Freight Train",
	"Lampadati Michelli GT",
	"Nagasaki Ultralight",
	"Buckingham Miljet",
	"Invade and Persuade Tank",
	"Vapid Minivan",
	"Vapid Minivan Custom",
	"HVY Mixer",
	"HVY Mixer",
	"Mammoth Mogul",
	"V-65 Molotok",
	"Pegassi Monroe",
	"Vapid The Liberator",
	"Bravado Apocalypse Sasquatch",
	"Bravado Future Shock Sasquatch",
	"Bravado Nightmare Sasquatch",
	"Maibatsu MonstroCiti",
	"Declasse Moonbeam",
	"Declasse Moonbeam Custom",
	"Lawn Mower",
	"Maibatsu Mule",
	"Maibatsu Mule",
	"Maibatsu Mule",
	"Maibatsu Mule Custom",
	"Maibatsu Mule",
	"Vulcar Nebula Turbo",
	"Principe Nemesis",
	"Vysser Neo",
	"Pfister Neon",
	"Truffade Nero",
	"Truffade Nero Custom",
	"Western Nightblade",
	"Imponte Nightshade",
	"HVY Nightshark",
	"Buckingham Nimbus",
	"Obey 9F",
	"Obey 9F Cabrio",
	"P-45 Nokota",
	"Lampadati Novak",
	"Obey Omnis",
	"Obey Omnis e-GT",
	"Benefactor BR8",
	"Declasse DR1",
	"Pegassi Oppressor",
	"Pegassi Oppressor Mk II",
	"Ubermacht Oracle XS",
	"Ubermacht Oracle",
	"Pegassi Osiris",
	"Nagasaki Outlaw",
	"MTL Packer",
	"Toundra Panthere",
	"Benefactor Panto",
	"Bravado Paradise",
	"Enus Paragon R",
	"Enus Paragon R (Armored)",
	"Ocelot Pariah",
	"Mammoth Patriot",
	"Mammoth Patriot Stretch",
	"Mammoth Patriot Mil-Spec",
	"Kurtz 31 Patrol Boat",
	"Prison Bus",
	"Festival Bus",
	"Shitzu PCJ 600",
	"Ocelot Penetrator",
	"Maibatsu Penumbra",
	"Maibatsu Penumbra FF",
	"Vapid Peyote",
	"Vapid Peyote Gasser",
	"Vapid Peyote Custom",
	"Pfister 811",
	"JoBuilt Phantom",
	"JoBuilt Phantom Wedge",
	"JoBuilt Phantom Custom",
	"Imponte Phoenix",
	"Cheval Picador",
	"Lampadati Pigalle",
	"Police Cruiser",
	"Police Cruiser",
	"Police Cruiser",
	"Unmarked Cruiser",
	"Police Bike",
	"Police Rancher",
	"Police Roadcruiser",
	"Police Transporter",
	"Police Maverick",
	"Brute Pony",
	"Brute Pony",
	"Dinka Postlude",
	"MTL Pounder",
	"MTL Pounder Custom",
	"Western Powersurge",
	"Bollokan Prairie",
	"Park Ranger",
	"Police Predator",
	"Declasse Premier",
	"Karin Previon",
	"Albany Primo",
	"Albany Primo Custom",
	"Prop Trailer",
	"Grotti X80 Proto",
	"Buckingham Pyro",
	"Annis 300R",
	"Vapid Radius",
	"Coil Raiden",
	"F-160 Raiju",
	"Trailer",
	"MTL Dune",
	"Declasse Rancher XL",
	"Declasse Rancher XL",
	"Dewbauchee Rapid GT",
	"Dewbauchee Rapid GT",
	"Dewbauchee Rapid GT Classic",
	"BF Raptor",
	"Western Rat Bike",
	"Vapid Ratel",
	"Rat-Loader",
	"Bravado Rat-Truck",
	"RC Bandito",
	"Pegassi Reaper",
	"Karin Rusty Rebel",
	"Karin Rebel",
	"Ubermacht Rebla GTS",
	"Western Reever",
	"Dundreary Regina",
	"Annis Remus",
	"Rental Shuttle Bus",
	"Vapid Retinue",
	"Vapid Retinue Mk II",
	"Ubermacht Revolter",
	"Declasse Rhapsody",
	"Ubermacht Rhinehart",
	"Rhino Tank",
	"Vapid Riata",
	"Police Riot",
	"RCV",
	"Ripley",
	"Obey Rocoto",
	"Western Rogue",
	"Chariot Romero Hearse",
	"Western Rampant Rocket",
	"Dinka RT3000",
	"JoBuilt Rubble",
	"Pegassi Ruffian",
	"Imponte Ruiner",
	"Imponte Ruiner 2000",
	"Imponte Ruiner",
	"Imponte Ruiner ZZ-8",
	"Bravado Rumpo",
	"Bravado Rumpo",
	"Bravado Rumpo Custom",
	"Hijak Ruston",
	"Annis S80RR",
	"Karin S95",
	"Declasse Sabre Turbo",
	"Declasse Sabre Turbo Custom",
	"Vapid Sadler",
	"Vapid Sadler",
	"Maibatsu Sanchez (livery)",
	"Maibatsu Sanchez",
	"LCC Sanctus",
	"Vapid Sandking XL",
	"Vapid Sandking SWB",
	"Savage",
	"Annis Savestra",
	"Ubermacht SC1",
	"HVY Apocalypse Scarab",
	"HVY Future Shock Scarab",
	"HVY Nightmare Scarab",
	"Benefactor Schafter",
	"Benefactor Schafter V12",
	"Benefactor Schafter LWB",
	"Benefactor Schafter V12 (Armored)",
	"Benefactor Schafter LWB (Armored)",
	"Benefactor Schlagen GT",
	"Benefactor Schwartzer",
	"Scorcher",
	"Declasse Scramjet",
	"Scrap Truck",
	"Western Seabreeze",
	"Speedophile Seashark",
	"Speedophile Seashark",
	"Speedophile Seashark",
	"Sea Sparrow",
	"Sparrow",
	"Sparrow",
	"Canis Seminole",
	"Canis Seminole Frontier",
	"Ubermacht Sentinel XS",
	"Ubermacht Sentinel",
	"Ubermacht Sentinel Classic",
	"Ubermacht Sentinel Classic Widebody",
	"Benefactor Serrano",
	"Dewbauchee Seven-70",
	"Buckingham Shamal",
	"Emperor ETR1",
	"Sheriff Cruiser",
	"Sheriff SUV",
	"Nagasaki Shinobi",
	"Nagasaki Shotaro",
	"Skylift",
	"Vapid Slamtruck",
	"Vapid Slamvan",
	"Vapid Lost Slamvan",
	"Vapid Slamvan Custom",
	"Vapid Apocalypse Slamvan",
	"Vapid Future Shock Slamvan",
	"Vapid Nightmare Slamvan",
	"Benefactor SM722",
	"Western Sovereign",
	"Dewbauchee Specter",
	"Dewbauchee Specter Custom",
	"Pegassi Speeder",
	"Pegassi Speeder",
	"Vapid Speedo",
	"Vapid Clown Van",
	"Vapid Speedo Custom",
	"Vapid Speedo Custom",
	"Mammoth Squaddie",
	"Shitzu Squalo",
	"Enus Stafford",
	"Declasse Stallion",
	"Declasse Burger Shot Stallion",
	"Vapid Stanier",
	"LF-22 Starling",
	"Grotti Stinger",
	"Grotti Stinger GT",
	"Grotti Itali GTO Stinger TT",
	"Brute Stockade",
	"Brute Stockade",
	"Zirconium Stratum",
	"Mammoth Streamer216",
	"Benefactor Streiter",
	"Dundreary Stretch",
	"B-11 Strikeforce",
	"Ocelot Stromberg",
	"Nagasaki Stryder",
	"Mallard",
	"Submersible",
	"Kraken",
	"Dinka Sugoi",
	"Karin Sultan",
	"Karin Sultan Classic",
	"Karin Sultan RS Classic",
	"Karin Sultan RS",
	"Shitzu Suntrap",
	"Enus Super Diamond",
	"Buckingham SuperVolito",
	"Buckingham SuperVolito Carbon",
	"Benefactor Surano",
	"BF Surfer",
	"BF Surfer",
	"BF Surfer Custom",
	"Cheval Surge",
	"Buckingham Swift",
	"Buckingham Swift Deluxe",
	"Ocelot Swinger",
	"Progen T20",
	"Taco Van",
	"Declasse Tahoma Coupe",
	"Obey Tailgater",
	"Obey Tailgater S",
	"Cheval Taipan",
	"Declasse Tampa",
	"Declasse Drift Tampa",
	"Declasse Weaponized Tampa",
	"Trailer",
	"Tanker",
	"Freight Train",
	"Taxi",
	"Karin Technical",
	"Karin Technical Aqua",
	"Karin Technical Custom",
	"Pegassi Tempesta",
	"Obey 10F",
	"Obey 10F Widebody",
	"Benefactor Terrorbyte",
	"Pegassi Tezeract",
	"Truffade Thrax",
	"Dinka Thrust",
	"Mammoth Thruster",
	"Lampadati Tigon",
	"Brute Tipper",
	"Tipper",
	"Titan",
	"Pegassi Toreador",
	"Pegassi Torero",
	"Pegassi Torero XO",
	"Declasse Tornado",
	"Declasse Tornado",
	"Declasse Tornado",
	"Declasse Tornado",
	"Declasse Tornado Custom",
	"Declasse Tornado Rat Rod",
	"Lampadati Toro",
	"Lampadati Toro",
	"Pegassi Toros",
	"Tourbus",
	"Towtruck",
	"Towtruck",
	"Trailer",
	"Trailer",
	"Trailer",
	"Tractor",
	"Stanley Fieldmaster",
	"Stanley Fieldmaster",
	"Mobile Operations Center",
	"Trailer",
	"Trailer",
	"Trailer",
	"Trailer",
	"Trailer",
	"Trailer",
	"Vom Feuer Anti-Aircraft Trailer",
	"Trashmaster",
	"Trashmaster",
	"Trailer",
	"Whippet Race Bike",
	"Endurex Race Bike",
	"Tri-Cycles Race Bike",
	"Vapid Trophy Truck",
	"Vapid Desert Raid",
	"Shitzu Tropic",
	"Shitzu Tropic",
	"Lampadati Tropos Rallye",
	"Tug",
	"Mammoth Tula",
	"Declasse Tulip",
	"Declasse Tulip M-100",
	"Grotti Turismo Classic",
	"Grotti Turismo R",
	"Trailer",
	"Overflod Tyrant",
	"Progen Tyrus",
	"Utility Truck",
	"Utility Truck",
	"Utility Truck",
	"Pegassi Vacca",
	"Shitzu Vader",
	"Dewbauchee Vagner",
	"Maxwell Vagrant",
	"Valkyrie",
	"Valkyrie MOD.0",
	"Declasse Vamos",
	"Emperor Vectre",
	"Velum",
	"Velum 5-Seater",
	"Bravado Verlierer",
	"Dinka Verus",
	"Buckingham Vestra",
	"Vetir",
	"Dinka Veto Classic",
	"Dinka Veto Modern",
	"Declasse Vigero",
	"Declasse Vigero ZX",
	"Vigilante",
	"Dinka Vindicator",
	"Albany Virgo",
	"Dundreary Virgo Classic Custom",
	"Dundreary Virgo Classic",
	"Ocelot Virtue",
	"Lampadati Viseris",
	"Grotti Visione",
	"Volatol",
	"Buckingham Volatus",
	"Coil Voltic",
	"Coil Rocket Voltic",
	"Declasse Voodoo Custom",
	"Declasse Voodoo",
	"Pegassi Vortex",
	"Albany V-STR",
	"Vulcar Warrener",
	"Vulcar Warrener HKR",
	"Albany Washington",
	"MTL Wastelander",
	"BF Weevil",
	"BF Weevil Custom",
	"Enus Windsor",
	"Enus Windsor Drop",
	"Vapid Winky",
	"Western Wolfsbane",
	"Ocelot XA-21",
	"Benefactor XLS",
	"Benefactor XLS (Armored)",
	"Declasse Yosemite",
	"Declasse Drift Yosemite",
	"Declasse Yosemite Rancher",
	"Bravado Youga",
	"Bravado Youga Classic",
	"Bravado Youga Classic 4x4",
	"Vapid Youga Custom",
	"Karin 190z",
	"Overflod Zeno",
	"Pegassi Zentorno",
	"RUNE Zhaba",
	"Ubermacht Zion",
	"Ubermacht Zion Cabrio",
	"Ubermacht Zion Classic",
	"Western Zombie Bobber",
	"Western Zombie Chopper",
	"Pegassi Zorrusso",
	"Annis ZR350",
	"Annis Apocalypse ZR380",
	"Annis Future Shock ZR380",
	"Annis Nightmare ZR380",
	"Truffade Z-Type"
}